name: youthcamp2016
favicon: null
layout_spectrum: 0.23719795979559422
typography_spectrum: 0.8377240188419819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.20694792899303138
  lightness: 0.35322384908795357
  saturation: 0.4413377770688385
  rhythmicContrast: 0.2762794718146324
purpose: []
